### PR TITLE
Added Platformio build. Moved remaining RS code to direct port writes…

### PR DESCRIPTION
**Pull request by sweetlilmre**
…. Removed all old commented code. Renamed direct port macros for readability. Changed read macros to check against HIGH / LOW constants for readability. Cleaned up Ps2Mouse constructor.

### CODE REVIEW

**Comment by sweetlilmre** [comment]
Here is the small refactor I did. Mostly just cleanup.

I was reading the PS2 spec documents and I think that there is still an issue around streaming mode.

With reset() not being called, the data reporting command will not be sent to the mouse. That may work for you on the KVM in that the mouse may be previously initialized, but may not work for others. I'm going to have a more careful look.

These changes are not yet tested on hardware, so consider this a draft PR. I'll confirm that things are working or not and let you know.

**Comment by sweetlilmre** [comment]
Hi again, I made a clean port off of Necroware's code, implementing the direct port access here: https://github.com/sweetlilmre/necroware-ps2-serial-firmware. If you follow the init logic from ino file through reset() you'll see what I mean. This is based off of this document: https://isdaman.com/alsos/hardware/mouse/ps2interface.htm

**Comment by morphinejh** [comment]
Seems reasonable, I'll give it a spin on the hardware for testing.

**Comment by sweetlilmre** [comment]
Hi, I tested this: https://github.com/sweetlilmre/necroware-ps2-serial-firmware on hardware in streaming mode and it works, I hope it works with your KVM setup. I'll test remote mode now. I haven't tested the refactor of your code as I think this implementation is closer to necroware's and more correct in terms of reset behaviour, so I will probably abandon this fork in favour of the above code, rebased on the original repo.

EDIT: tested both modes work well. Also validated remote mode against original fw and behaviour seems identical.

**Comment by morphinejh** [comment]
Good to know, I haven't tested yet myself. What reset behavior are you implying is abnormal?

**Comment by morphinejh** [comment]
Oh, I think you mean:
```
  //TODO: Cleanup
  //Identify streaming mode or not.
  //mouse->reset(!digitalRead(JP34));
```

I probably should uncomment that one for good measure. I think the behavior of PS/2 is to start in streaming mode at power up. I did test this a lot; but I never tested adding it back. Seems like you did, so I may add that to the list of changes.

**Comment by sweetlilmre** [comment]
Yes, that's it, after reset the mouse defaults to streaming mode, but the default configuration has data reporting disabled. The reset() method call sends the enable data reporting command. Technically the mouse should not stream data until this is sent. I'm not sure how your code is working without it.

**Comment by morphinejh** [comment]
For better or worse, I'm sure its the KVM. I tested your code, and while it seems to work, the mouse pointers is uncontrollable. Clicks work okay.

At first I thought it was the KVM not taking the `.SampleRate()`;  but I'm not sure yet. I also found on that same webpage to set the Sample Rate in Streaming mode, you need to disable reporting first - I don't think that's happening in anyone's code (yet). I think this KVM may be extremely loose in the standard or very strict.  Still testing to find out.

**Comment by sweetlilmre** [comment]
That's interesting, I also assumed the kvm might be at play. I'll re-read the docs on sample rate, but reporting mode should definitely be disabled in my code if streaming is enabled (default on reset), check the code path in the reset method.

**Comment by sweetlilmre** [comment]
Actually I may have misunderstood what you were saying there. I'll have another look.

**Comment by morphinejh** [comment]
> That's interesting, I also assumed the kvm might be at play. I'll re-read the docs on sample rate, but reporting mode should definitely be disabled in my code if streaming is enabled (default on reset), check the code path in the reset method.

It is disabled going into reset, but enabled on the way out. Which is correct. The odd part is `.SampleRate()` is set after reset finishes. So it is adjusting the rate **_after_** the reset returns.

From the PS/2 Mouse Interfacing page:
> If the mouse is in Stream mode, the host should disable data reporting (command 0xF5) before sending any other commands.

Which means the sampling rate should be set during the reset, or data reporting should be disabled before sending the new rate.

**Comment by sweetlilmre** [comment]
Got it. Should be simple enough to fix. It's late here so won't do it tonight, but may have a gap tomorrow.

**Comment by sweetlilmre** [comment]
I've pushed a change to disable data reporting when sending commands. I'm not sure if this will make a difference, please test if you have a chance: [https://github.com/sweetlilmre/necroware-ps2-serial-firmware](https://github.com/sweetlilmre/necroware-ps2-serial-firmware)

I've tested my side and it seems to work (without KVM obvs).

**Comment by sweetlilmre** [comment]
I've made further progress with the firmware, adding in mouse wheel support. I also think that perhaps it's the reset call that is causing issues with your KWM. I can add in some code to disable that as a test case for you if you're interested?

I'll be nuking my fork of your repo, catch me here if you're keen: https://github.com/sweetlilmre/ps2-serial-mouse-adapter

**Comment by sweetlilmre** [comment]
All code moved here: https://github.com/sweetlilmre/ps2-serial-mouse-adapter

**Comment by sweetlilmre** [comment]
https://github.com/sweetlilmre/ps2-serial-mouse-adapter/tree/stream_and_wheel
This branch has an experimental hack for your KVM switch. Enable both jumpers, the adapter will be in 3-button Logitech mode and will not call the reset command. If this works then we've got to the root of the issue. I spent some time today looking at PS2 behaviour, and a call to reset causes a > 400ms delay before the PS2 mouse starts responding. I believe this is what is causing the issue with your KVM.
I've managed to find a small Belkin (I think) KVM-ish type switch although I don't have cables unfortunately, I'll try and see if I can make some up and test with that. Could you give me the name and model of your KVM?

**Comment by morphinejh** [comment]
If you open up issue tracking on your repo I can post it there as well.

It is a Trendnet TK-423K. It is a PS/2 and/or USB KVM. I'd like to try it on a PS/2 only KVM if I can find one.  I did try your other branch as well with some modifications. I didn't find a good solution there either. I'll give the stream_and_wheel branch a test too;  here in the near future.

**Comment by sweetlilmre** [comment]
Here you go, opened an issue to track this: https://github.com/sweetlilmre/ps2-serial-mouse-adapter/issues/1

**Pull request closed without merging**
